In [81]:
# We can
# Add, Multiply, Saprate two arrays
# Compaire two arrays

In [82]:
import numpy as np

In [83]:
a = np.random.rand((10))
b = np.random.rand((10))

In [84]:
a

array([0.39643436, 0.96818599, 0.58131119, 0.52423047, 0.03671587,
       0.21542049, 0.88863213, 0.27951708, 0.8680408 , 0.5713813 ])

In [85]:
b

array([0.62463955, 0.05803307, 0.36174888, 0.38856384, 0.98415481,
       0.89446016, 0.10379823, 0.78036743, 0.60685183, 0.38452581])

In [86]:
a+b         #Add array b in array a

array([1.02107391, 1.02621906, 0.94306007, 0.91279431, 1.02087068,
       1.10988065, 0.99243036, 1.05988451, 1.47489263, 0.95590711])

In [87]:
a-b         #Seprate array b from array a

array([-0.22820519,  0.91015292,  0.21956231,  0.13566663, -0.94743894,
       -0.67903968,  0.7848339 , -0.50085035,  0.26118897,  0.18685549])

In [88]:
a*b         #Multply array a by array b

array([0.24762858, 0.0561868 , 0.21028867, 0.203697  , 0.0361341 ,
       0.19268504, 0.09223844, 0.21812603, 0.52677215, 0.21971086])

In [89]:
2*a         #Multiply array a by 2

array([0.79286872, 1.93637198, 1.16262238, 1.04846094, 0.07343174,
       0.43084097, 1.77726425, 0.55903416, 1.7360816 , 1.14276259])

In [90]:
1/a         #Inverse array a

array([ 2.5224857 ,  1.0328594 ,  1.720249  ,  1.90755795, 27.23618033,
        4.64208405,  1.12532506,  3.57759889,  1.15201958,  1.75014479])

In [91]:
a           #Print array a

array([0.39643436, 0.96818599, 0.58131119, 0.52423047, 0.03671587,
       0.21542049, 0.88863213, 0.27951708, 0.8680408 , 0.5713813 ])

In [92]:
a>0.5       #Get bool value for those element who is greter then 0.5

array([False,  True,  True,  True, False, False,  True, False,  True,
        True])

In [93]:
a[a>0.5]    #Get all values who is greter then 0.5 

array([0.96818599, 0.58131119, 0.52423047, 0.88863213, 0.8680408 ,
       0.5713813 ])