In [4]:
import numpy as np

In [5]:
x = np.array([1,7,9,8,5])       #Create array with 5 elements

In [6]:
x[4]        #Get 4th index element of array x

5

In [7]:
x[x>5]      #Get array element who is greter then 5

array([7, 9, 8])

In [8]:
x[[2,1]]    #Get element at index 2 and index 1 by fanci indexing

array([9, 7])

In [9]:
x = np.random.rand(10,10)
x

array([[0.53900589, 0.9248762 , 0.73091735, 0.49073723, 0.94926342,
        0.40785573, 0.1484195 , 0.74759201, 0.09357343, 0.65854242],
       [0.07164602, 0.8194294 , 0.30070001, 0.90607777, 0.55240294,
        0.52135432, 0.35164738, 0.79859353, 0.91242213, 0.54991827],
       [0.41922996, 0.71898648, 0.69173782, 0.03484944, 0.51500791,
        0.36956628, 0.59065661, 0.87776658, 0.66423185, 0.72044526],
       [0.26971347, 0.19568078, 0.32557721, 0.25209956, 0.19665758,
        0.45143187, 0.02081902, 0.24759508, 0.90651654, 0.82007169],
       [0.02972992, 0.71352181, 0.0322869 , 0.29108603, 0.29188316,
        0.39387804, 0.89065533, 0.99123315, 0.87254476, 0.72704737],
       [0.37222683, 0.21013766, 0.90939119, 0.51517318, 0.20734256,
        0.31993135, 0.05828752, 0.93203727, 0.33120223, 0.40232735],
       [0.27719527, 0.92077055, 0.84523711, 0.15003603, 0.18654842,
        0.40334909, 0.83677141, 0.29248595, 0.28970741, 0.15284314],
       [0.64965015, 0.29581135, 0.7451880

In [10]:
x[0]        #Get first row

array([0.53900589, 0.9248762 , 0.73091735, 0.49073723, 0.94926342,
       0.40785573, 0.1484195 , 0.74759201, 0.09357343, 0.65854242])

In [11]:
x[0][4]     #Get 4th value of first row 

0.9492634196329536

In [12]:
x[1:10:2]   #Get odd rows from 1 till 10 with step value 2

array([[0.07164602, 0.8194294 , 0.30070001, 0.90607777, 0.55240294,
        0.52135432, 0.35164738, 0.79859353, 0.91242213, 0.54991827],
       [0.26971347, 0.19568078, 0.32557721, 0.25209956, 0.19665758,
        0.45143187, 0.02081902, 0.24759508, 0.90651654, 0.82007169],
       [0.37222683, 0.21013766, 0.90939119, 0.51517318, 0.20734256,
        0.31993135, 0.05828752, 0.93203727, 0.33120223, 0.40232735],
       [0.64965015, 0.29581135, 0.74518807, 0.99427136, 0.1482074 ,
        0.74011005, 0.29563975, 0.13177452, 0.25508749, 0.4326121 ],
       [0.25183473, 0.59179601, 0.63782547, 0.22386784, 0.26894841,
        0.75684801, 0.32660296, 0.39563212, 0.07373863, 0.89853381]])

In [13]:
x[::,0:4]   #Get start 4th coloums from array, "::" show all rows

array([[0.53900589, 0.9248762 , 0.73091735, 0.49073723],
       [0.07164602, 0.8194294 , 0.30070001, 0.90607777],
       [0.41922996, 0.71898648, 0.69173782, 0.03484944],
       [0.26971347, 0.19568078, 0.32557721, 0.25209956],
       [0.02972992, 0.71352181, 0.0322869 , 0.29108603],
       [0.37222683, 0.21013766, 0.90939119, 0.51517318],
       [0.27719527, 0.92077055, 0.84523711, 0.15003603],
       [0.64965015, 0.29581135, 0.74518807, 0.99427136],
       [0.3198146 , 0.90161578, 0.46136319, 0.90421182],
       [0.25183473, 0.59179601, 0.63782547, 0.22386784]])

In [14]:
#Example
#Make square shape with border 1 but having 0 in inner element

In [15]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])