In [1]:
import numpy as np

In [2]:
x = np.array([1,7,9,8,5])       #Create array with 5 elements

In [7]:
x[4]        #Get 4th index element of array x

5

In [8]:
x[x>5]      #Get array element who is greter then 5

array([7, 9, 8])

In [11]:
x[[2,1]]    #Get element at index 2 and index 1 by fanci indexing

array([9, 7])

In [13]:
x = np.random.rand(10,10)
x

array([[0.90779177, 0.20242484, 0.09705827, 0.762934  , 0.21420582,
        0.89893089, 0.076776  , 0.79340796, 0.57527807, 0.61590671],
       [0.25600124, 0.46631575, 0.97877031, 0.83015437, 0.37463448,
        0.74911181, 0.9045365 , 0.67104507, 0.00114716, 0.04712202],
       [0.42313016, 0.62131964, 0.09286135, 0.9206791 , 0.81585492,
        0.68558431, 0.70771747, 0.66425628, 0.34043532, 0.45449921],
       [0.9359457 , 0.22422524, 0.08327891, 0.97822198, 0.20550149,
        0.02867606, 0.42466873, 0.02654426, 0.0021664 , 0.07742218],
       [0.1797557 , 0.49362417, 0.44647465, 0.89145826, 0.32877746,
        0.04599058, 0.83884927, 0.70337371, 0.38378724, 0.67141688],
       [0.79882372, 0.31321199, 0.56252565, 0.49604658, 0.62016817,
        0.7089699 , 0.97432535, 0.51532347, 0.00682488, 0.89861778],
       [0.32707146, 0.67958278, 0.42927885, 0.62377263, 0.94585643,
        0.90645309, 0.03590862, 0.59247706, 0.72700361, 0.7261319 ],
       [0.2874629 , 0.35890493, 0.4413416

In [15]:
x[0]        #Get first row

array([0.90779177, 0.20242484, 0.09705827, 0.762934  , 0.21420582,
       0.89893089, 0.076776  , 0.79340796, 0.57527807, 0.61590671])

In [16]:
x[0][4]     #Get 4th value of first row 

0.21420581512101566

In [19]:
x[1:10:2]   #Get odd rows from 1 till 10 with step value 2

array([[0.25600124, 0.46631575, 0.97877031, 0.83015437, 0.37463448,
        0.74911181, 0.9045365 , 0.67104507, 0.00114716, 0.04712202],
       [0.9359457 , 0.22422524, 0.08327891, 0.97822198, 0.20550149,
        0.02867606, 0.42466873, 0.02654426, 0.0021664 , 0.07742218],
       [0.79882372, 0.31321199, 0.56252565, 0.49604658, 0.62016817,
        0.7089699 , 0.97432535, 0.51532347, 0.00682488, 0.89861778],
       [0.2874629 , 0.35890493, 0.4413416 , 0.45164829, 0.11803836,
        0.81943015, 0.41540686, 0.85084304, 0.97962436, 0.79161457],
       [0.87054487, 0.78201296, 0.61756425, 0.93725028, 0.77649533,
        0.20919206, 0.47162917, 0.19774464, 0.24568643, 0.88314364]])

In [22]:
x[::,0:4]   #Get start 4th coloums from array, "::" show all rows

array([[0.90779177, 0.20242484, 0.09705827, 0.762934  ],
       [0.25600124, 0.46631575, 0.97877031, 0.83015437],
       [0.42313016, 0.62131964, 0.09286135, 0.9206791 ],
       [0.9359457 , 0.22422524, 0.08327891, 0.97822198],
       [0.1797557 , 0.49362417, 0.44647465, 0.89145826],
       [0.79882372, 0.31321199, 0.56252565, 0.49604658],
       [0.32707146, 0.67958278, 0.42927885, 0.62377263],
       [0.2874629 , 0.35890493, 0.4413416 , 0.45164829],
       [0.60588754, 0.59292884, 0.5580014 , 0.73857104],
       [0.87054487, 0.78201296, 0.61756425, 0.93725028]])

In [24]:
#Example
#Make square shape with border 1 but having 0 in inner element

In [26]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])