In [2]:
import numpy as np

In [3]:
x = np.array([1,7,9,8,5])       #Create array with 5 elements

In [4]:
x[4]        #Get 4th index element of array x

5

In [5]:
x[x>5]      #Get array element who is greter then 5

array([7, 9, 8])

In [6]:
x[[2,1]]    #Get element at index 2 and index 1 by fanci indexing

array([9, 7])

In [7]:
x = np.random.rand(10,10)
x

array([[0.5984551 , 0.17803444, 0.87389904, 0.60062083, 0.63687012,
        0.63594821, 0.17722077, 0.45464765, 0.18411563, 0.21627645],
       [0.37521508, 0.32058422, 0.2744547 , 0.23747724, 0.89210207,
        0.85179275, 0.99727154, 0.66463406, 0.43785599, 0.42468117],
       [0.84544116, 0.16319141, 0.81514384, 0.77586377, 0.67739013,
        0.86559619, 0.12555853, 0.0340751 , 0.90300478, 0.25567533],
       [0.56295185, 0.8978739 , 0.59913257, 0.62263634, 0.26663052,
        0.06841319, 0.5538429 , 0.66009162, 0.60606838, 0.39676383],
       [0.44780434, 0.97013122, 0.95872013, 0.27389807, 0.0766023 ,
        0.05882269, 0.95597995, 0.28088156, 0.17504032, 0.28910295],
       [0.74862644, 0.30249878, 0.48922403, 0.36268893, 0.24062046,
        0.39900741, 0.84423388, 0.00523366, 0.33719244, 0.74209884],
       [0.34716902, 0.41015018, 0.23156818, 0.20488298, 0.25739553,
        0.48205689, 0.86793946, 0.37177584, 0.2302216 , 0.83592986],
       [0.40234489, 0.96854656, 0.1813749

In [8]:
x[0]        #Get first row

array([0.5984551 , 0.17803444, 0.87389904, 0.60062083, 0.63687012,
       0.63594821, 0.17722077, 0.45464765, 0.18411563, 0.21627645])

In [9]:
x[0][4]     #Get 4th value of first row 

0.6368701178296214

In [10]:
x[1:10:2]   #Get odd rows from 1 till 10 with step value 2

array([[0.37521508, 0.32058422, 0.2744547 , 0.23747724, 0.89210207,
        0.85179275, 0.99727154, 0.66463406, 0.43785599, 0.42468117],
       [0.56295185, 0.8978739 , 0.59913257, 0.62263634, 0.26663052,
        0.06841319, 0.5538429 , 0.66009162, 0.60606838, 0.39676383],
       [0.74862644, 0.30249878, 0.48922403, 0.36268893, 0.24062046,
        0.39900741, 0.84423388, 0.00523366, 0.33719244, 0.74209884],
       [0.40234489, 0.96854656, 0.18137496, 0.53155644, 0.36910028,
        0.15130307, 0.20785233, 0.36575897, 0.18871759, 0.98153317],
       [0.64402758, 0.56429355, 0.82440193, 0.71144938, 0.31546436,
        0.98170172, 0.68048544, 0.27410514, 0.94847874, 0.36412691]])

In [11]:
x[::,0:4]   #Get start 4th coloums from array, "::" show all rows

array([[0.5984551 , 0.17803444, 0.87389904, 0.60062083],
       [0.37521508, 0.32058422, 0.2744547 , 0.23747724],
       [0.84544116, 0.16319141, 0.81514384, 0.77586377],
       [0.56295185, 0.8978739 , 0.59913257, 0.62263634],
       [0.44780434, 0.97013122, 0.95872013, 0.27389807],
       [0.74862644, 0.30249878, 0.48922403, 0.36268893],
       [0.34716902, 0.41015018, 0.23156818, 0.20488298],
       [0.40234489, 0.96854656, 0.18137496, 0.53155644],
       [0.49563707, 0.56043568, 0.87174816, 0.15519822],
       [0.64402758, 0.56429355, 0.82440193, 0.71144938]])

In [12]:
#Example
#Make square shape with border 1 but having 0 in inner element

In [13]:
x = np.ones((5,5))
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x[1:-1,1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])