In [8]:
import numpy as np

In [12]:
x = np.array([10,9,8,6,11])

In [13]:
np.sqrt(x)              #Get SqureRoot

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [14]:
np.power(x,2)           #Get Squre

array([100,  81,  64,  36, 121], dtype=int32)

In [15]:
y = [7,1,2,3,-1]

In [19]:
np.maximum(x,y)         #Get max value from array x and y index by index

array([10,  9,  8,  6, 11])