In [25]:
import numpy as np

In [26]:
x = np.array([10,9,7,10,7])

In [27]:
np.mean(x)      #Get mean/avg value

8.6

In [28]:
np.cumsum(x)    #Comulative sum

array([10, 19, 26, 36, 43], dtype=int32)

In [29]:
np.cumprod(x)   #Comulative multiple

array([   10,    90,   630,  6300, 44100], dtype=int32)

In [30]:
y = x > 7       #Get all elements who is greter then 7 in array
y

array([ True,  True, False,  True, False])

In [31]:
y.sum()         #Get/Sum all TRUE value

3

In [32]:
y.any()         #Check any element is TRUE

True

In [33]:
y.all()         #Check all element is TRUE

False

In [37]:
x.sort()        #Lets sort x array
x

array([ 7,  7,  9, 10, 10])

In [35]:
np.unique(x)    #Get unique elements from array x

array([ 7,  9, 10])