In [17]:
import numpy as np

In [18]:
x = np.random.randn(3,2)
x

array([[-0.76105625, -0.15898317],
       [ 0.04349108, -1.05355931],
       [ 1.38937244,  0.13990574]])

In [19]:
y = np.random.randn(2,3)
y

array([[-0.25313364,  0.77366397,  2.14091356],
       [ 2.12829067, -1.64516365, -0.75048425]])

In [20]:
x.dot(y)                #Get dot product of x and y arrays

array([[-0.14571345, -0.32724847, -1.51004129],
       [-2.25328949,  1.76692495,  0.88379032],
       [-0.05393682,  0.84473956,  2.86952925]])

In [21]:
x.transpose()           #Get Transpose of x array

array([[-0.76105625,  0.04349108,  1.38937244],
       [-0.15898317, -1.05355931,  0.13990574]])

In [22]:
x.trace()

-1.8146155579283798