### Reshape

In [2]:
import numpy as np

In [4]:
x = np.random.randn(4,5)
x

array([[ 0.48487665, -0.79300821, -1.38997612,  1.24118147, -0.09100165],
       [ 0.91044749,  0.7686195 , -0.86661186, -0.24279597,  1.18023011],
       [ 0.95018672,  0.5432596 , -1.50713264, -1.39827776,  1.33009093],
       [-1.07220479,  0.69561468,  0.5671292 ,  1.71330037,  0.14462479]])

In [5]:
x.reshape((2,2,5))              #row major order

array([[[ 0.48487665, -0.79300821, -1.38997612,  1.24118147,
         -0.09100165],
        [ 0.91044749,  0.7686195 , -0.86661186, -0.24279597,
          1.18023011]],

       [[ 0.95018672,  0.5432596 , -1.50713264, -1.39827776,
          1.33009093],
        [-1.07220479,  0.69561468,  0.5671292 ,  1.71330037,
          0.14462479]]])

In [7]:
x.reshape((2,2,5), order='F')   #colume major order

array([[[ 0.48487665, -0.79300821, -1.38997612,  1.24118147,
         -0.09100165],
        [ 0.95018672,  0.5432596 , -1.50713264, -1.39827776,
          1.33009093]],

       [[ 0.91044749,  0.7686195 , -0.86661186, -0.24279597,
          1.18023011],
        [-1.07220479,  0.69561468,  0.5671292 ,  1.71330037,
          0.14462479]]])

In [9]:
x.reshape((2,2,-1))

array([[[ 0.48487665, -0.79300821, -1.38997612,  1.24118147,
         -0.09100165],
        [ 0.91044749,  0.7686195 , -0.86661186, -0.24279597,
          1.18023011]],

       [[ 0.95018672,  0.5432596 , -1.50713264, -1.39827776,
          1.33009093],
        [-1.07220479,  0.69561468,  0.5671292 ,  1.71330037,
          0.14462479]]])

In [11]:
x               #Two dimentional array

array([[ 0.48487665, -0.79300821, -1.38997612,  1.24118147, -0.09100165],
       [ 0.91044749,  0.7686195 , -0.86661186, -0.24279597,  1.18023011],
       [ 0.95018672,  0.5432596 , -1.50713264, -1.39827776,  1.33009093],
       [-1.07220479,  0.69561468,  0.5671292 ,  1.71330037,  0.14462479]])

In [13]:
x.ravel()       #Convert in one dimentional array - 1st way

array([ 0.48487665, -0.79300821, -1.38997612,  1.24118147, -0.09100165,
        0.91044749,  0.7686195 , -0.86661186, -0.24279597,  1.18023011,
        0.95018672,  0.5432596 , -1.50713264, -1.39827776,  1.33009093,
       -1.07220479,  0.69561468,  0.5671292 ,  1.71330037,  0.14462479])

In [14]:
x.flatten()     #Convert in one dimentional array - 2nd way

array([ 0.48487665, -0.79300821, -1.38997612,  1.24118147, -0.09100165,
        0.91044749,  0.7686195 , -0.86661186, -0.24279597,  1.18023011,
        0.95018672,  0.5432596 , -1.50713264, -1.39827776,  1.33009093,
       -1.07220479,  0.69561468,  0.5671292 ,  1.71330037,  0.14462479])