### Reshape

In [3]:
import numpy as np

In [4]:
x = np.random.randn(4,5)
x

array([[ 1.61365889,  0.47737879, -0.15499397, -0.00312597, -0.15638305],
       [-1.74233203,  2.14211919, -0.48225965, -0.97029668,  1.38500205],
       [-0.65759396,  0.13618578, -0.34534027,  0.68118784,  0.26165605],
       [-1.06316148, -0.83935595,  0.88271889,  0.18296054,  0.64248484]])

In [5]:
x.reshape((2,2,5))              #row major order

array([[[ 1.61365889,  0.47737879, -0.15499397, -0.00312597,
         -0.15638305],
        [-1.74233203,  2.14211919, -0.48225965, -0.97029668,
          1.38500205]],

       [[-0.65759396,  0.13618578, -0.34534027,  0.68118784,
          0.26165605],
        [-1.06316148, -0.83935595,  0.88271889,  0.18296054,
          0.64248484]]])

In [6]:
x.reshape((2,2,5), order='F')   #colume major order

array([[[ 1.61365889,  0.47737879, -0.15499397, -0.00312597,
         -0.15638305],
        [-0.65759396,  0.13618578, -0.34534027,  0.68118784,
          0.26165605]],

       [[-1.74233203,  2.14211919, -0.48225965, -0.97029668,
          1.38500205],
        [-1.06316148, -0.83935595,  0.88271889,  0.18296054,
          0.64248484]]])

In [7]:
x.reshape((2,2,-1))

array([[[ 1.61365889,  0.47737879, -0.15499397, -0.00312597,
         -0.15638305],
        [-1.74233203,  2.14211919, -0.48225965, -0.97029668,
          1.38500205]],

       [[-0.65759396,  0.13618578, -0.34534027,  0.68118784,
          0.26165605],
        [-1.06316148, -0.83935595,  0.88271889,  0.18296054,
          0.64248484]]])

### Conversion

In [8]:
x               #Two dimentional array

array([[ 1.61365889,  0.47737879, -0.15499397, -0.00312597, -0.15638305],
       [-1.74233203,  2.14211919, -0.48225965, -0.97029668,  1.38500205],
       [-0.65759396,  0.13618578, -0.34534027,  0.68118784,  0.26165605],
       [-1.06316148, -0.83935595,  0.88271889,  0.18296054,  0.64248484]])

In [9]:
x.ravel()       #Convert in one dimentional array - 1st way

array([ 1.61365889,  0.47737879, -0.15499397, -0.00312597, -0.15638305,
       -1.74233203,  2.14211919, -0.48225965, -0.97029668,  1.38500205,
       -0.65759396,  0.13618578, -0.34534027,  0.68118784,  0.26165605,
       -1.06316148, -0.83935595,  0.88271889,  0.18296054,  0.64248484])

In [10]:
x.flatten()     #Convert in one dimentional array - 2nd way

array([ 1.61365889,  0.47737879, -0.15499397, -0.00312597, -0.15638305,
       -1.74233203,  2.14211919, -0.48225965, -0.97029668,  1.38500205,
       -0.65759396,  0.13618578, -0.34534027,  0.68118784,  0.26165605,
       -1.06316148, -0.83935595,  0.88271889,  0.18296054,  0.64248484])

### Concatenate

In [12]:
x = [[1,3,5], [7,9,0]]                  #List            
arr1 = np.array(x)                      #Convert this list into numpy array
y = [[11,13,15], [17,19,10]]            #List  
arr2 = np.array(y)                      #Convert this list into numpy array                           
np.concatenate((arr1, arr2), axis=0)    #Concate - row wise (v stack)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [14]:
np.concatenate((arr1, arr2), axis=1)    #Concate - colume wise (h stack)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

In [15]:
np.vstack((arr1, arr2))                 #Concate - row wise (v stack)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [16]:
np.hstack((arr1, arr2))                 #Concate - colume wise (h stack)

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

### Split

In [29]:
x = [1,4,5,6,7,9,1,4]       #One dimensional array
x

[1, 4, 5, 6, 7, 9, 1, 4]

In [25]:
d = np.array(x)             #Convert array into np array

In [26]:
np.split(d, [2,5])          #Split np array rowwise (One dimentional)

[array([1, 4]), array([5, 6, 7]), array([9, 1, 4])]

In [31]:
y = [[1,4,5,6,7,9,1,4], [11,14,15,16,17,19,11,14]] #Two dimensional array
y

[[1, 4, 5, 6, 7, 9, 1, 4], [11, 14, 15, 16, 17, 19, 11, 14]]

In [32]:
d = np.array(y)             #Convert array into np array

In [35]:
np.split(d, [4,6], axis=1)  #Split np array by columewise (two dimentional)

[array([[ 1,  4,  5,  6],
        [11, 14, 15, 16]]),
 array([[ 7,  9],
        [17, 19]]),
 array([[ 1,  4],
        [11, 14]])]

In [36]:
np.split(d, [1], axis=0)

[array([[1, 4, 5, 6, 7, 9, 1, 4]]), array([[11, 14, 15, 16, 17, 19, 11, 14]])]